services:
  - type: static_site
    name: new-beginning-mbc
    autoDeploy: true
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=86400
      - path: /dashboard/*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
