services:
  - type: web
    name: new-beginning-mbc
    runtime: static
    autoDeploy: true
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=86400
    envVars:
      - key: NODE_VERSION
        value: ""
